user_agent = "yalich-basic-example"

[languages.python]
manifests = [
  "examples/basic/pyproject.toml"
]
[languages.python.overrides]
"cheroot" = { license = "BSD-3-Clause" }

[languages.rust]
manifests = [
  "examples/basic/Cargo.toml"
]

[languages.node]
manifests = [
  "examples/basic/package.json"
]
